stages:
  - lint
  - build
  - test
  - deploy

default:
  image: alpine

Linter Python:
  stage: lint 
  image: python:3.9.22-alpine
  tags: [devops-test]
  script:
    - pip install flake8 flake8-sarif
    - flake8 --version
    - flake8 server/server.py
  allow_failure: true

Build Docker images:
  stage: build
  image:
    name: gcr.io/kaniko-project/executor:v1.23.2-debug
    entrypoint: [""]
  tags: [devops-test]
  script:
    - /kaniko/executor
      --context "${CI_PROJECT_DIR}"
      --dockerfile "${CI_PROJECT_DIR}/server/Dockerfile"
      --destination "localhost:5000/server:${CI_COMMIT_TAG}"

Testing:
  stage: test
  tags: [devops-test]
  script:
    - echo "Test"

Deploy to staging:
  stage: deploy
  tags: [devops-test]
  script:
    - echo "deploy"