stages:
  - lint
  - build
  - deploy
  - test
  - notify

default:
  image: alpine

Linter Python:
  stage: lint 
  image: python:3.9.22-alpine
  tags: [devops-test]
  script:
    - pip install flake8 flake8-sarif
    - flake8 --version
    - flake8 server/server.py
  allow_failure: true

Build Docker images:
  stage: build
  image:
    name: gcr.io/kaniko-project/executor:v1.23.2-debug
    entrypoint: [""]
  tags: [devops-test]
  script:
    - /kaniko/executor
      --context "${CI_PROJECT_DIR}/server"
      --dockerfile "${CI_PROJECT_DIR}/server/Dockerfile"
      --destination "localhost:5000/server:${CI_COMMIT_TAG}"

Deploy to staging:
  stage: deploy
  image: docker
  services: 
    - name: docker:dind
      entrypoint: ["sh", "-c", "dockerd-entrypoint.sh --insecure-registry=registry:5000"]
  tags: [devops-test]
  variables: 
    DOCKER_HOST: tcp://localhost:2376/
  script:
    - echo "deploy"
    - ls
    - docker exec -it staging sh -c "echo a && echo b"
    # - docker run -d registry:5000/server:latest
    - sh ${CI_PROJECT_DIR}/notify.sh ✅


Testing:
  stage: test
  tags: [devops-test]
  script:
    - echo "Test"
  needs:
   - "Deploy to staging"


Notification for Errors:
  stage: notify
  image: alpine/curl
  tags: [devops-test]
  script:
    - sh ${CI_PROJECT_DIR}/notify.sh ❌
  when: on_failure