stages:
  - lint
  - build
  - test
  - deploy

default:
  image: alpine

Linter Python:
  stage: lint 
  image: python:3.9.22-alpine
  tags: [devops-test]
  script:
    - pip install flake8 flake8-sarif
    - flake8 --version
    - flake8 server/server.py
  allow_failure: true

Build Docker images:
  stage: build
  image: docker 
  tags: [devops-test]
  services: 
    - docker:dind
  script:
    - cd server
    - docker build -t server-python .
  artifacts:
    paths:
      - public

Push docker image:
  stage: push-image
  image: docker
  tags: [devops-test]
  services: 
    - docker:dind
  script:
    - echo "Push"
  needs:
    - job: "Build Docker images"
      artifacts: true

Testing:
  stage: test
  tags: [devops-test]
  script:
    - echo "Test"

Deploy to staging:
  stage: deploy
  tags: [devops-test]
  script:
    - echo "deploy"