stages:
  - lint
  - build
  - test
  - deploy

default:
  image: alpine

Linter Python:
  stage: lint 
  image: alpine/flake8
  tags: [devops-test]
  script: 
    - flake --version
    - flake server/server.py


Build Docker images:
  stage: build
  image: docker 
  tags: [devops-test]
  script:
    - cd server
    - docker build -t server-python .

Testing:
  stage: test
  tags: [devops-test]
  script:
    - echo "Test"

Deploy to staging:
  stage: deploy
  tags: [devops-test]
  script:
    - echo "deploy"